version: '3.8'

services:
  # MySQL Database
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: fluento-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/db:/docker-entrypoint-initdb.d
    networks:
      - fluento-network

  # Backend Spring Boot
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fluento-backend
    restart: unless-stopped
    ports:
      - "9000:8080"
    environment:
      - OPENAI_API_KEY=AIzaSyCp7ISJg72yQGRagJkK1mFw3OM7ssTloVk
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - CHAT_MODEL=gemini-2.5-flash
      - LOG_PATH=/var/log/fluento

    depends_on:
      - mysql
    networks:
      - fluento-network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fluento-frontend
    restart: unless-stopped
    ports:
      - "1234:80"
    depends_on:
      - backend
    networks:
      - fluento-network

volumes:
  mysql_data:
    driver: local

networks:
  fluento-network:
    driver: bridge

volumes:
  - ./logs:/var/log/fluento