version: '3.8'

services:
  mysql:
    image: theanhn28/fluento-mysql:latest
    container_name: fluento-mysql-hub
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data_hub:/var/lib/mysql
    networks:
      - fluento
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 30s

  backend:
    image: theanhn28/fluento-backend:latest
    container_name: fluento-backend-hub
    restart: unless-stopped
    ports:
      - "9000:8080"
    environment:
      - OPENAI_API_KEY= <>
      - CHAT_MODEL=gemini-2.5-flash
      - ELEVENLABS_API_KEY= <>
      - LOG_PATH=/var/log/fluento

    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fluento

  # Frontend React from Docker Hub
  frontend:
    image: theanhn28/fluento-frontend:latest
    container_name: fluento-frontend-hub
    restart: unless-stopped
    ports:
      - "1234:80"
    depends_on:
      - backend
    networks:
      - fluento

networks:
  fluento:
    driver: bridge

volumes:
  - ./logs:/var/log/fluento

