/** Shared topic code → localized label (en / vi). */
export const TOPICS_EN = {
  LIFE: "Life",
  TECHNOLOGY: "Technology",
  CULTURE: "Culture",
  FOOD: "Food",
  HEALTH: "Health",
  EDUCATION: "Education",
  FITNESS: "Fitness",
  MENTAL_HEALTH: "Mental health",
  TRAVEL: "Travel",
  TOURISM: "Tourism",
  COUNTRIES: "Countries",
  LANDMARKS: "Landmarks",
  BUSINESS: "Business",
  SCIENCE: "Science",
  ENTERTAINMENT: "Entertainment",
  SOCIETY: "Society",
};

export const TOPICS_VI = {
  LIFE: "Cuộc sống",
  TECHNOLOGY: "Công nghệ",
  CULTURE: "Văn hoá",
  FOOD: "Ẩm thực",
  HEALTH: "Sức khỏe",
  EDUCATION: "Giáo dục",
  FITNESS: "Thể hình",
  MENTAL_HEALTH: "Sức khỏe tinh thần",
  TRAVEL: "Du lịch",
  TOURISM: "Du lịch thương mại",
  COUNTRIES: "Các quốc gia",
  LANDMARKS: "Danh lam thắng cảnh",
  BUSINESS: "Kinh doanh",
  SCIENCE: "Khoa học",
  ENTERTAINMENT: "Giải trí",
  SOCIETY: "Xã hội",
};
