/** Shared topic code → localized label (en / vi). */
export const TOPICS_EN = {
  LIFE: "Life",
  TECHNOLOGY: "Technology",
  CULTURE: "Culture",
  FOOD: "Food",
  ENVIRONMENT: "Environment",
  HEALTH: "Health",
  EDUCATION: "Education",
  FITNESS: "Fitness",
  YOGA: "Yoga",
  NUTRITION: "Nutrition",
  MENTAL_HEALTH: "Mental health",
  MEDICINE: "Medicine",
  TRAVEL: "Travel",
  TOURISM: "Tourism",
  COUNTRIES: "Countries",
  LANDMARKS: "Landmarks",
  TRANSPORTATION: "Transportation",
  WEATHER: "Weather",
  BUSINESS: "Business",
  SCIENCE: "Science",
  ECONOMICS: "Economics",
  MARKETING: "Marketing",
  FINANCE: "Finance",
  STARTUPS: "Startups",
  ECOMMERCE: "E-commerce",
  ART: "Art",
  HISTORY: "History",
  LITERATURE: "Literature",
  PHILOSOPHY: "Philosophy",
  PSYCHOLOGY: "Psychology",
  MUSIC: "Music",
  MOVIES: "Movies",
  THEATRE: "Theatre",
  FASHION: "Fashion",
  GAMES: "Games",
  SPORTS: "Sports",
  ENTERTAINMENT: "Entertainment",
  POLITICS: "Politics",
  RELIGION: "Religion",
  SOCIETY: "Society",
  SHOPPING: "Shopping",
  HOUSEWORK: "Housework",
  RELATIONSHIPS: "Relationships",
  PETS: "Pets",
  HOLIDAYS: "Holidays",
  CLIMATE_CHANGE: "Climate change",
  SUSTAINABILITY: "Sustainability",
  GLOBALIZATION: "Globalization",
  POVERTY: "Poverty",
  HUMAN_RIGHTS: "Human rights",
  PARENTING: "Parenting",
  MARRIAGE: "Marriage",
  COMMUNITY: "Community",
  VOLUNTEERING: "Volunteering",
  TRADITIONS: "Traditions",
};

export const TOPICS_VI = {
  LIFE: "Cuộc sống",
  TECHNOLOGY: "Công nghệ",
  CULTURE: "Văn hoá",
  FOOD: "Ẩm thực",
  ENVIRONMENT: "Môi trường",
  HEALTH: "Sức khỏe",
  EDUCATION: "Giáo dục",
  FITNESS: "Thể hình",
  YOGA: "Yoga",
  NUTRITION: "Dinh dưỡng",
  MENTAL_HEALTH: "Sức khỏe tinh thần",
  MEDICINE: "Y học",
  TRAVEL: "Du lịch",
  TOURISM: "Du lịch thương mại",
  COUNTRIES: "Các quốc gia",
  LANDMARKS: "Danh lam thắng cảnh",
  TRANSPORTATION: "Giao thông vận tải",
  WEATHER: "Thời tiết",
  BUSINESS: "Kinh doanh",
  SCIENCE: "Khoa học",
  ECONOMICS: "Kinh tế học",
  MARKETING: "Marketing",
  FINANCE: "Tài chính",
  STARTUPS: "Khởi nghiệp",
  ECOMMERCE: "Thương mại điện tử",
  ART: "Nghệ thuật",
  HISTORY: "Lịch sử",
  LITERATURE: "Văn học",
  PHILOSOPHY: "Triết học",
  PSYCHOLOGY: "Tâm lý học",
  MUSIC: "Âm nhạc",
  MOVIES: "Phim ảnh",
  THEATRE: "Sân khấu",
  FASHION: "Thời trang",
  GAMES: "Trò chơi",
  SPORTS: "Thể thao",
  ENTERTAINMENT: "Giải trí",
  POLITICS: "Chính trị",
  RELIGION: "Tôn giáo",
  SOCIETY: "Xã hội",
  SHOPPING: "Mua sắm",
  HOUSEWORK: "Việc nhà",
  RELATIONSHIPS: "Các mối quan hệ",
  PETS: "Thú cưng",
  HOLIDAYS: "Kỳ nghỉ & Lễ hội",
  CLIMATE_CHANGE: "Biến đổi khí hậu",
  SUSTAINABILITY: "Phát triển bền vững",
  GLOBALIZATION: "Toàn cầu hoá",
  POVERTY: "Nghèo đói",
  HUMAN_RIGHTS: "Nhân quyền",
  PARENTING: "Nuôi dạy con cái",
  MARRIAGE: "Hôn nhân",
  COMMUNITY: "Cộng đồng",
  VOLUNTEERING: "Tình nguyện",
  TRADITIONS: "Truyền thống",
};
