server:
  port: ${BACKEND_PORT}
  servlet:
    context-path: /api

spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  reactor:
    debug-agent:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          signer-key: 29A1E019A311440FF025957809748C9D
          access-token-valid-duration: 15 # in minutes
          refresh-token-valid-duration: 3 # in day
    client:
      registration:
        google:
          client-id: "${GOOGLE_CLIENT_ID}"
          client-secret: "${GOOGLE_CLIENT_SECRET}"
          redirect-uri: "${GOOGLE_REDIRECT_URI}"
          scope: openid,profile,email
      provider:
        google:
          authorization-uri: https://accounts.google.com/o/oauth2/v2/auth # fixed
          api-uri: https://oauth2.googleapis.com # fixed
          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo # fixed
  ai:
    openai:
      api-key: "${GEMINI_API_KEY}"
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash