server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://${mysqldb:localhost}:3306/fluento"
    username: "root"
    password: "Admin@123"
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  reactor:
    debug-agent:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          signer-key: 29A1E019A311440FF025957809748C9D
          access-token-valid-duration: 15 # in minutes
          refresh-token-valid-duration: 3 # in day
    client:
      registration:
        google:
          client-id: 940316326175-8jma9br9b2j1cjgqu992v3a693euvr6c.apps.googleusercontent.com # fixed
          client-secret: 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 # fixed
          redirect-uri: http://localhost:5173/oauth/authenticate # modify as needed
          scope: openid, profile, email
      provider:
        google:
          authorization-uri: https://accounts.google.com/o/oauth2/v2/auth # fixed
          api-uri: https://oauth2.googleapis.com # fixed
          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo # fixed
  ai:
    openai:
      api-key: AIzaSyCp7ISJg72yQGRagJkK1mFw3OM7ssTloVk
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash